Improve doc with response schema
herbsjs/buchu pull request #20
Opened 2020-09-22 22:59 UTC by maikmb

Improve of `usecase` type with response schema for describe usecase response doc.

![image](https://user-images.githubusercontent.com/4916896/93945729-dcdb8e80-fd0d-11ea-9a35-9df1628c3464.png)

2020-09-22 23:17 UTC, jhomarolo commented on src/usecase.js
> +        return this._requestSchema;
This will break the linter checker

2020-09-22 23:18 UTC, jhomarolo requested changes
Hi Maik, your PR break the eslint checker. Can you fix it?

2020-09-23 14:04 UTC, maikmb commented on src/usecase.js
> +        return this._requestSchema;
Hi @jhomarolo !
Fixed!

2020-09-23 14:05 UTC, maikmb commented
> Hi Maik, your PR break the eslint checker. Can you fix it?



> Hi Maik, your PR break the eslint checker. Can you fix it?

Fixed!

2020-09-23 14:58 UTC, dalssoft commented
It seems to be missing complex test scenarios for `response` like arrays `[String]`, etc

2020-09-23 14:58 UTC, dalssoft requested changes
Please, improve the tests with complex scenarios

2020-09-25 18:29 UTC, maikmb commented
Hi @dalssoft !
I improved the tests with complex scenarios to response schema. Can you see please?

2020-09-25 23:07 UTC, dalssoft approved these changes

2020-09-25 23:07 UTC, merged