Add sync/async operators to Authorize step
herbsjs/buchu pull request #35
Opened 2021-05-15 03:58 UTC by maikmb

Fixes and changes #

## Proposed Changes

1. Add sync/async operators to authorize step

2021-06-01 10:28 UTC, jhomarolo commented
Hi Maik, could you please, update the documentation?

2021-06-01 10:44 UTC, jhomarolo requested changes
Hi @maikmb, could you please, update the documentation?

2021-06-01 10:44 UTC, jhomarolo commented on examples/todoapp/usecases/listItems.js
> +        authorize: async (user) => Promise.resolve(user.isAdmin ? Ok() : Err()),
Why use a promise resolve here?

2021-06-07 02:16 UTC, maikvortx commented on examples/todoapp/usecases/listItems.js
> +        authorize: async (user) => Promise.resolve(user.isAdmin ? Ok() : Err()),
I forgot to remove this code. Adjusted!

2021-06-07 14:31 UTC, merged